version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r JavaWeb.zip target/JavaWeb.war appspec.yml restart.sh
      - aws s3 cp JavaWeb.zip s3://bharathsdelivion/
artifacts:
  files:
    - target/JavaWeb.war
